routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CompanyController;
use App\Http\Controllers\EmployeeController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/login',[App\Http\Controllers\LoginController::class,'index'])->name('login');
Route::post('/login', [\App\Http\Controllers\LoginController::class, 'login'])->name('login.post');

Route::middleware([ 'auth'])->group(function () {
    Route::post('/logout', [\App\Http\Controllers\LoginController::class, 'logout'])->name('logout');
    Route::get('/',[App\Http\Controllers\DashboardController::class,'index'])->name('dashboard');
    Route::resource('/companies', CompanyController::class);
    Route::resource('/employees', EmployeeController::class);
});

resources/views/companies.blade.php
@extends('layout.master')
@section('title','Dashboard')
@section('top_scripts')


<link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.3.0/css/bootstrap.min.css" rel="stylesheet" />
<link href="https://cdn.datatables.net/2.0.7/css/dataTables.bootstrap5.css" rel="stylesheet" />
@endsection
@section('style')
@endsection
@section('content')
<main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4" style="margin-left: 220px;">
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
      <h1 class="h2">Companies</h1>
      <div class="btn-toolbar mb-2 mb-md-0">
      </div>
    </div>
  {{-- content --}}
  <div class="main-body">
    <div class="container">
     <section class="content">
      <div class="container-fluid">
       <div class="row">
        <div class="col-12">
         <div class="card">
          <div class="card-header">
           <button type="button" data-bs-toggle="modal" data-bs-target="#company" class="btn btn-block btn-outline-info btn-sm col-2">Add Company</button>
          </div>
          <!-- /.card-header -->
          <div class="card-body">
           {{-- table --}}
           <table id="example" class="table table-striped" style="width:100%">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>logo</th>
                    <th>Description</th>
                    <th>Mobile</th>
                    <th>Annual Turnover</th>
                    <th>Created By</th>
                    <th>Created At</th>
                    <th>view</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($companies as $company)


                <tr>
                    <td>{{$company->name}}</td>
                    <td>
                        <div class="col-3">  <img src="{{ asset('storage/' .$company->logo) }}" alt="logo" width="100%"></div>
                    </td>
                    <td>{{$company->description}}</td>
                    <td>{{$company->mobile}}</td>
                    <td>{{$company->annual_turnover}}</td>
                    <td>{{$company['createdBy']->name}}</td>
                    <td>{{\Carbon\Carbon::parse($company->created_at)->format('j-F-Y ,H:i a')}}</td>
                <td><a href="{{route('companies.show', ['company' => $company->id])}}" class="btn btn-outline-primary btn-xs"><i data-feather="eye"></i></a></td>
                </tr>

                @endforeach
            </tbody>
        </table>
           {{-- /table --}}
          </div>
          <!-- /.card-body -->
         </div>
         <!-- /.card -->
        </div>
       </div>
      </div>
     </section>
    </div>
   </div>
  </main>

  <!-- Modal -->
<div class="modal fade" id="company" tabindex="-1" aria-labelledby="companyLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
     <div class="modal-content">
      <div class="modal-header">
       <h5 class="modal-title" id="exampleModalLabel">Create Company</h5>
       <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
       </button>
      </div>

      <form method="post" action="{{route('companies.store')}}" enctype="multipart/form-data">
       @csrf
       <div class="modal-body">
        <div class="card-body">
         <div class="form-group">
          <label for="name">Name<span class="m-l-5 text-danger"> *</span></label>
          <input type="text" class="form-control" id="" name="name" value="" placeholder="Enter Company Name" />
          <span class="text-danger error-text name_error"></span>
         </div>
         <div class="form-group">
          <label for="description" class="form-label">Description<span class="m-l-5 text-danger"> *</span></label>
          <textarea name="description" class="form-control"  rows="5">{{ old('description') }}</textarea>
          <span class="text-danger error-text Email_error"></span>
         </div>
         <div class="form-group">
          <label for="">Contact Number<span class="m-l-5 text-danger"> *</span></label>
          <input type="text" class="form-control" name="mobile" value="" id="" placeholder="Enter Contact Number" />
         </div>
         <div class="form-group">
            <label for="name">Annul TurnOver<span class="m-l-5 text-danger"> *</span></label>
            <input type="text" class="form-control" id="" name="annual_turnover" value="" />
            <span class="text-danger error-text name_error"></span>
           </div>
         <div class="form-group">
          <label for="exampleInputFile">Logo<span class="m-l-5 text-danger"> *</span></label>
          <div class="input-group">
           <div class="custom-file">
            <input type="file" class="custom-file-input" name="logo" id="logo" />
           </div>
          </div>
          <span class="text-danger error-text Logo_error"></span>
         </div>
        </div>
       </div>
       <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">Save</button>
       </div>
      </form>
     </div>
    </div>
   </div>
@endsection
@section('bottom_scripts')
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.3.0/js/bootstrap.bundle.min.js"></script>
<script src="https://cdn.datatables.net/2.0.7/js/dataTables.js"></script>
<script src="https://cdn.datatables.net/2.0.7/js/dataTables.bootstrap5.js"></script>
<script>
    new DataTable('#example')
</script>
;
@endsection

resources/views/company_detaile.blade.php
@extends('layout.master')
@section('title','Dashboard')
@section('top_scripts')
@endsection
@section('style')
@endsection
@section('content')
<main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4" style="margin-left: 220px;">
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
      <h1 class="h2">Company Detaile</h1>
      <div class="btn-toolbar mb-2 mb-md-0">
      </div>
    </div>
  {{-- content --}}
  <section class="content">
    <div class="card card-primary card-outline">
        <div class="card-body box-profile">
            <div class="text-center">



                <img class="profile-user-img img-fluid img-circle" width="30%" src="{{ asset('storage/' .$company->logo) }}" alt="User profile picture">



            </div>

            <h3 class="profile-username text-center">{{$company->name}}</h3>

            <p class="text-muted text-center">{{$company->description}}</p>

            <ul class="list-group list-group-unbordered mb-3">
                <li class="list-group-item">
                    <b>Contact Number</b> <a class="float-right">{{$company->mobile}}</a>
                </li>
                <li class="list-group-item">
                    <b>Annua Turnover</b> <a class="float-right">{{$company->annual_turnover}}</a>
                </li>
                <li class="list-group-item">
                    <b>Created By</b> <a class="float-right">{{$company['createdBy']->name}}</a>
                </li>
                <li class="list-group-item">
                    <b>Created At</b> <a class="float-right">{{\Carbon\Carbon::parse($company->created_at)->format('j-F-Y ,H:i a')}}</a>
                </li>

            </ul>

            <a  class="btn btn-primary btn-block col-2" href="{{route('companies.edit', ['company' => $company->id])}}" ><b>Edit</b></a>
            <form method="post" action="{{route('companies.destroy', ['company' => $company->id])}}">
                @method('delete')
                @csrf
                <button type="submit"  class="btn btn-danger btn-block col-2">
                    <b>Delete</b>
            </button>
            </form>
        </div>
        <!-- /.card-body -->
    </div>
</section>
  </main>
@endsection
@section('bottom_scripts')
@endsection

resources/views/dashboard.blade.php
@extends('layout.master')
@section('title','Dashboard')
@section('top_scripts')
@endsection
@section('style')
@endsection
@section('content')
<main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4" style="margin-left: 220px;">
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
      <h1 class="h2">Dashboard</h1>
      <div class="btn-toolbar mb-2 mb-md-0">
      </div>
    </div>
  {{-- content --}}
  </main>
@endsection
@section('bottom_scripts')
@endsection

resources/views/edit_companies.blade.php
@extends('layout.master')
@section('title','Dashboard')
@section('top_scripts')
@endsection
@section('style')
@endsection
@section('content')
<main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4" style="margin-left: 220px;">
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
      <h1 class="h2">Dashboard</h1>
      <div class="btn-toolbar mb-2 mb-md-0">
      </div>
    </div>
  {{-- content --}}
  <div class="row">
    <form method="put" action="{{route('companies.update', ['company' => $company->id])}}" enctype="multipart/form-data">

        @csrf
        <div class="modal-body">
         <div class="card-body">
          <div class="form-group">
           <label for="name">Name<span class="m-l-5 text-danger"> *</span></label>
           <input type="text" class="form-control" id="" name="name" value="{{$company->name}}" placeholder="Enter Company Name" />
           <span class="text-danger error-text name_error"></span>
          </div>
          <div class="form-group">
           <label for="description" class="form-label">Description<span class="m-l-5 text-danger"> *</span></label>
           <textarea name="description" class="form-control" value="{{$company->description}}"  rows="5">{{$company->description}}</textarea>
           <span class="text-danger error-text Email_error"></span>
          </div>
          <div class="form-group">
           <label for="">Contact Number<span class="m-l-5 text-danger"> *</span></label>
           <input type="text" class="form-control" name="mobile" value="{{$company->mobile}}" id="" placeholder="Enter Contact Number" />
          </div>
          <div class="form-group">
             <label for="name">Annul TurnOver<span class="m-l-5 text-danger"> *</span></label>
             <input type="text" class="form-control" id="" value="{{$company->annual_turnover}}"  name="annual_turnover"  />
             <span class="text-danger error-text name_error"></span>
            </div>
          <div class="form-group">
           <label for="exampleInputFile">Logo<span class="m-l-5 text-danger"> *</span></label>
           <div class="input-group">
            <div class="custom-file">
             <input type="file" class="custom-file-input" name="logo" id="logo" />
            </div>
           </div>
           <span class="text-danger error-text Logo_error"></span>
          </div>
         </div>
        </div>
        <div class="modal-footer">
         <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
         <button type="submit" class="btn btn-primary">Update</button>
        </div>
       </form>
  </div>
  </main>
@endsection
@section('bottom_scripts')
@endsection

resources/views/edit_employees.blade.php
@extends('layout.master')
@section('title','Dashboard')
@section('top_scripts')
@endsection
@section('style')
@endsection
@section('content')
<main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4" style="margin-left: 220px;">
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
      <h1 class="h2">Dashboard</h1>
      <div class="btn-toolbar mb-2 mb-md-0">
      </div>
    </div>
  {{-- content --}}
  <div class="row">
    <form  method="post" action="{{route('employees.update', ['employee' => $employee->id])}}" enctype="multipart/form-data">
        @method('put')
        @csrf
    <div class="card-body ">
      <div class="row">
      <div class="form-group col-6 inputname" >
        <label for="name">Name<span class="m-l-5 text-danger"> *</span></label>
        <input type="text" class="form-control" id="" name="name" value="{{$employee->name}}" >
        <span class="text-danger error-text name_error"></span>
      </div>

      <div class="form-group col-6 inputname">
        <label for="name">Join Date<span class="m-l-5 text-danger"> *</span></label>
        <input type="date" class="form-control" id="" name="join_date" value="{{$employee->join_date}}" >
        <span class="text-danger error-text LastName_error"></span>
      </div>

      <div class="form-group col-6 inputname">
        <label for="Email">Email address<span class="m-l-5 text-danger"> *</span></label>
        <input type="email" class="form-control" id="" value="{{$employee->email}}" name="email" placeholder="Enter email">
        <span class="text-danger error-text email_error"></span>
      </div>
      <div class="form-group col-6 inputname">
        <label for="indusrty">Phone</label>
        <input type="text" class="form-control" name="phone" value="{{$employee->phone}}" id="" >
        <span class="text-danger error-text phone_error"></span>
      </div>
      </div>
      <div class="form-group">
        <label for="">Company<span class="m-l-5 text-danger"> *</span></label>
        <select class="form-control" name="company_id" id="">
          @foreach($companies as $company)
          <option value="{{$company->id}}" {{ old('company_id',$employee->company_id) == $company->id ? 'selected' : ''}}>{{$company->name}}</option>

          @endforeach

        </select>
        <span class="text-danger error-text company_id_error"></span>
      </div>

      <div class="form-group">
          <label for="exampleInputFile">Image<span class="m-l-5 text-danger"> *</span></label>
          <div class="input-group">
           <div class="custom-file">
            <input type="file" class="custom-file-input" name="image" id="logo" />
           </div>
          </div>
          <span class="text-danger error-text image_error"></span>
         </div>

    </div>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-primary">update</button>
  </div>
</form>
       </form>
  </div>
  </main>
@endsection
@section('bottom_scripts')
@endsection

resources/views/employe_detaile.blade.php
@extends('layout.master')
@section('title','Dashboard')
@section('top_scripts')
@endsection
@section('style')
@endsection
@section('content')
<main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4" style="margin-left: 220px;">
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
      <h1 class="h2">Employee </h1>
      <div class="btn-toolbar mb-2 mb-md-0">
      </div>
    </div>
  {{-- content --}}
  <section class="content">
    <div class="card card-primary card-outline">
        <div class="card-body box-profile">
            <div class="text-center">
                <img class="profile-user-img img-fluid img-circle" width="30%" src="{{ asset('storage/' .$employee->image) }}" alt="User profile picture">

            </div>
            <h3 class="profile-username text-center">{{$employee->name}}</h3>
            <ul class="list-group list-group-unbordered mb-3">
                <li class="list-group-item">
                    <b>Company</b> <a class="float-right">{{$employee['company']->name}}</a>
                </li>
                <li class="list-group-item">
                    <b>Contact Number</b> <a class="float-right">{{$employee->phone}}</a>
                </li>
                <li class="list-group-item">
                    <b>email</b> <a class="float-right">{{$employee->email}}</a>
                </li>
                <li class="list-group-item">
                    <b>Created By</b> <a class="float-right">{{$employee['createdBy']->name}}</a>
                </li>
                <li class="list-group-item">
                    <b>Created At</b> <a class="float-right">{{\Carbon\Carbon::parse($employee->created_at)->format('j-F-Y ,H:i a')}}</a>
                </li>

            </ul>

            <a  class="btn btn-primary btn-block col-2" href="{{route('employees.edit', ['employee' => $employee->id])}}" ><b>Edit</b></a>
            <form method="post" action="{{route('employees.destroy', ['employee' => $employee->id])}}">
               @method('delete')
                @csrf
                <button type="submit"  class="btn btn-danger btn-block col-2">
                    <b>Delete</b>
            </button>
            </form>
        </div>
        <!-- /.card-body -->
    </div>
</section>
  </main>
@endsection
@section('bottom_scripts')
@endsection

resources/views/employees.blade.php
@extends('layout.master')
@section('title','Dashboard')
@section('top_scripts')
@endsection
@section('style')
<link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.3.0/css/bootstrap.min.css" rel="stylesheet" />
<link href="https://cdn.datatables.net/2.0.7/css/dataTables.bootstrap5.css" rel="stylesheet" />
@endsection
@section('content')
<main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4" style="margin-left: 220px;">
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
      <h1 class="h2">Employees</h1>
      <div class="btn-toolbar mb-2 mb-md-0">
      </div>
    </div>
  {{-- content --}}
  <div class="main-body">
    <div class="container">
     <section class="content">
      <div class="container-fluid">
       <div class="row">
        <div class="col-12">
         <div class="card">
          <div class="card-header">
           <button type="button" data-bs-toggle="modal" data-bs-target="#employees" class="btn btn-block btn-outline-info btn-sm col-2">Add Employee</button>
          </div>
          <!-- /.card-header -->
          <div class="card-body">
           {{-- table --}}
           <table id="example" class="table table-striped" style="width:100%">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>image</th>
                    <th>company</th>
                    <th>Mobile</th>
                    <th>email</th>
                    <th>Join Date</th>
                    <th>Created By</th>
                    <th>Created At</th>
                    <th>view</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($employees as $employee)


                <tr>
                    <td>{{$employee->name}}</td>
                    <td>
                        <div class="col-3">  <img src="{{ asset('storage/' .$employee->image) }}" alt="image" width="100%"></div>
                    </td>
                    <td>{{$employee['company']->name}}</td>
                    <td>{{$employee->phone}}</td>
                    <td>{{$employee->email}}</td>
                    <td>{{\Carbon\Carbon::parse($employee->join_date)->format('j-F-Y ')}}</td>
                    <td>{{$employee['createdBy']->name}}</td>
                    <td>{{\Carbon\Carbon::parse($employee->created_at)->format('j-F-Y ,H:i a')}}</td>
                <td><a href="{{route('employees.show', ['employee' => $employee->id])}}" class="btn btn-outline-primary btn-xs"><i data-feather="eye"></i></a></td>
                </tr>

                @endforeach
            </tbody>
        </table>
          </div>
          <!-- /.card-body -->
         </div>
         <!-- /.card -->
        </div>
       </div>
      </div>
     </section>
    </div>
   </div>
  </main>
@endsection
<!-- Modal -->
<div class="modal fade" id="employees" tabindex="-1" aria-labelledby="employeeLabel" aria-hidden="true">
    <div class="modal-dialog  modal-lg">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Create Employee</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <form id="EmployeeForm" method="post" action="{{route('employees.store')}}" enctype="multipart/form-data">
              @csrf
          <div class="card-body ">
            <div class="row">
            <div class="form-group col-6 inputname" >
              <label for="name">Name<span class="m-l-5 text-danger"> *</span></label>
              <input type="text" class="form-control" id="" name="name" value="" >
              <span class="text-danger error-text name_error"></span>
            </div>

            <div class="form-group col-6 inputname">
              <label for="name">Join Date<span class="m-l-5 text-danger"> *</span></label>
              <input type="date" class="form-control" id="" name="join_date" value="" >
              <span class="text-danger error-text LastName_error"></span>
            </div>

            <div class="form-group col-6 inputname">
              <label for="Email">Email address<span class="m-l-5 text-danger"> *</span></label>
              <input type="email" class="form-control" id="" name="email" placeholder="Enter email">
              <span class="text-danger error-text email_error"></span>
            </div>
            <div class="form-group col-6 inputname">
              <label for="indusrty">Phone</label>
              <input type="text" class="form-control" name="phone" value="" id="" >
              <span class="text-danger error-text phone_error"></span>
            </div>
            </div>
            <div class="form-group">
              <label for="">Company<span class="m-l-5 text-danger"> *</span></label>
              <select class="form-control" name="company_id" id="">
                @foreach($companies as $company)
                <option value="{{$company->id}}">{{$company->name}}</option>
                @endforeach

              </select>
              <span class="text-danger error-text company_id_error"></span>
            </div>

            <div class="form-group">
                <label for="exampleInputFile">Image<span class="m-l-5 text-danger"> *</span></label>
                <div class="input-group">
                 <div class="custom-file">
                  <input type="file" class="custom-file-input" name="image" id="logo" />
                 </div>
                </div>
                <span class="text-danger error-text image_error"></span>
               </div>

          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button type="submit" class="btn btn-primary">Save</button>
        </div>
  </form>
      </div>
    </div>
  </div>
@section('bottom_scripts')
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.3.0/js/bootstrap.bundle.min.js"></script>
<script src="https://cdn.datatables.net/2.0.7/js/dataTables.js"></script>
<script src="https://cdn.datatables.net/2.0.7/js/dataTables.bootstrap5.js"></script>
<script>
    new DataTable('#example')
</script>
@endsection

resources/views/login.blade.php
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../../../favicon.ico">

    <title>Signin Template for Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />

    <!-- Custom styles for this template -->
    <link href="signin.css" rel="stylesheet">
    <style>
        html,
body {
  height: 100%;
}

body {
  display: -ms-flexbox;
  display: flex;
  -ms-flex-align: center;
  align-items: center;
  padding-top: 40px;
  padding-bottom: 40px;
  background-color: #f5f5f5;
}

.form-signin {
  width: 100%;
  max-width: 330px;
  padding: 15px;
  margin: auto;
}
.form-signin .checkbox {
  font-weight: 400;
}
.form-signin .form-control {
  position: relative;
  box-sizing: border-box;
  height: auto;
  padding: 10px;
  font-size: 16px;
}
.form-signin .form-control:focus {
  z-index: 2;
}
.form-signin input[type="email"] {
  margin-bottom: -1px;
  border-bottom-right-radius: 0;
  border-bottom-left-radius: 0;
}
.form-signin input[type="password"] {
  margin-bottom: 10px;
  border-top-left-radius: 0;
  border-top-right-radius: 0;
}

        </style>
  </head>
  <body class="text-center">
    <form class="form-signin"  method="POST" action="{{ route('login') }}">
        @csrf
      <h1 class="h3 mb-3 font-weight-normal">Please sign in</h1>
      <label for="inputEmail" class="sr-only">Email address</label>
      <input type="email" name="email" value="{{ old('email') }}" id="inputEmail" class="form-control" placeholder="Email address" required autofocus>
      @error('email')
            <div class="alert alert-danger"><em>{{ $message }}</em></div>
        @enderror
      <label for="inputPassword" class="sr-only">Password</label>
      <input type="password" name="password" value="{{ old('password') }}" id="inputPassword" class="form-control" placeholder="Password" required>
      @error('password')
      <div class="alert alert-danger"><em>{{ $message }}</em></div>
      @enderror
      <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
    </form>
  </body>
</html>